export const initialUsers = [
  {
    id: 'usr-1',
    name: 'Александр Громов',
    login: process.env.ADMIN_LOGIN || 'admin',
    password: process.env.ADMIN_PASSWORD_HASH || '$2a$10$aGkS8h96LI6qn1Ca.aLUa.XvpxE0tMbfiY.uOPtYkbCfyZpDBFOJu',
    role: 'Tech Lead / Admin',
    roleType: 'admin',
    department: 'Engineering',
    email: 'a.gromov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    pin: process.env.ADMIN_PIN_HASH || '$2a$10$Q/IUsVYACtPrHRHIMdXRqeg9heShRh8AtJMU/dcOXhfkSSVbyf83m',
    isActive: true
  },
  {
    id: 'usr-2',
    name: 'Нурбек Ғани Нурбекулы',
    login: 'nurbek',
    password: 'user123',
    role: 'Backend Engineer',
    roleType: 'member',
    department: 'Engineering',
    email: 'n.ghani@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-3',
    name: 'Мейрамов Ернур Ерланович',
    login: 'ernur',
    password: 'user123',
    role: 'Frontend Lead',
    roleType: 'member',
    department: 'Engineering',
    email: 'e.meiramov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-4',
    name: 'Насыров Абылай Даниярулы',
    login: 'abylay',
    password: 'user123',
    role: 'Fullstack Developer',
    roleType: 'member',
    department: 'Engineering',
    email: 'a.nasyrov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-5',
    name: 'Надыров Марат Абдирехимович',
    login: 'marat',
    password: 'user123',
    role: 'Product Manager',
    roleType: 'member',
    department: 'Product & Agile',
    email: 'm.nadyrov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-6',
    name: 'Баубеков Николай Владимирович',
    login: 'nikolay',
    password: 'user123',
    role: 'QA Automation Lead',
    roleType: 'member',
    department: 'Quality Assurance',
    email: 'n.baubekov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-7',
    name: 'Исмаилов Рамзан Денильбекович',
    login: 'ramzan',
    password: 'user123',
    role: 'UI/UX Designer',
    roleType: 'member',
    department: 'Design Team',
    email: 'r.ismailov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-8',
    name: 'Лоскутов Максим Викторович',
    login: 'maksim',
    password: 'user123',
    role: 'System Architect / DBA',
    roleType: 'member',
    department: 'Engineering',
    email: 'm.loskutov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-9',
    name: 'Немировский Михаил Юрьевич',
    login: 'mikhail',
    password: 'user123',
    role: 'DevOps / SRE Engineer',
    roleType: 'member',
    department: 'Engineering',
    email: 'm.nemirovsky@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-10',
    name: 'Қайратов БіржанЧИК Қайратұлы',
    login: 'birzhan',
    password: 'user123',
    role: 'Scrum Master / Agile Coach',
    roleType: 'member',
    department: 'Product & Agile',
    email: 'b.kairatov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  },
  {
    id: 'usr-11',
    name: 'Нурманов Рауан Конысбаевич',
    login: 'rauan',
    password: 'user123',
    role: 'Data Analyst / BI Specialist',
    roleType: 'member',
    department: 'Product & Agile',
    email: 'r.nurmanov@corp.lan',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80',
    pin: 'user123',
    isActive: true
  }
];

export const initialSprints = [
  {
    id: 'sprint-1',
    name: 'Sprint 24: Core Pulse 12 Release',
    startDate: '2026-07-01',
    endDate: '2026-07-14',
    goal: 'Внедрение RBAC, оптимизация 60 FPS, централизованный сервер и сетевой доступ для 12 сотрудников',
    isActive: true
  },
  {
    id: 'sprint-2',
    name: 'Sprint 25: Analytics & Integrations',
    startDate: '2026-07-15',
    endDate: '2026-07-28',
    goal: 'Расширенная отчетность по отделам и автоматические уведомления в Telegram/Slack',
    isActive: false
  }
];

export const initialTasks = [
  {
    id: 'NEX-101',
    title: 'Настройка центрального сервера на ноутбуке для команды из 12 человек',
    description: 'Развернуть Node.js + Express + Socket.io сервер на центральном ноутбуке с доступом из локальной сети (LAN). Обеспечить хранение данных в db.json.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-9',
    assignee: 'usr-9',
    assigneeGroupId: 'grp-1',
    storyPoints: 8,
    estimatedHours: 16,
    loggedHours: 16,
    sprintId: 'sprint-1',
    tags: ['Architecture', 'Backend', 'DevOps'],
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-04T12:00:00Z',
    subtasks: [
      { id: 'sub-1', title: 'Установить express, cors, socket.io', completed: true },
      { id: 'sub-2', title: 'Реализовать синхронизацию db.json', completed: true }
    ],
    comments: []
  },
  {
    id: 'NEX-102',
    title: 'Реализация входа по Логину и Паролю для новых сотрудников',
    description: 'Обеспечить возможность Администратору создавать учетные записи с Логином и Паролем. Перевести модальное окно авторизации на форму ввода учетных данных.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-3',
    assignee: 'usr-3',
    assigneeGroupId: 'grp-1',
    storyPoints: 5,
    estimatedHours: 12,
    loggedHours: 12,
    sprintId: 'sprint-1',
    tags: ['Security', 'Frontend', 'UI/UX'],
    createdAt: '2026-07-02T10:00:00Z',
    updatedAt: '2026-07-04T14:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-103',
    title: 'Мгновенная синхронизация через WebSockets (Socket.io) на всех ПК',
    description: 'Когда сотрудник перемещает задачу на своем ноутбуке, у всех остальных коллег в офисе доска должна обновляться автоматически без перезагрузки браузера.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-2',
    assignee: 'usr-2',
    assigneeGroupId: 'grp-1',
    storyPoints: 8,
    estimatedHours: 20,
    loggedHours: 20,
    sprintId: 'sprint-1',
    tags: ['Backend', 'Architecture', 'Frontend'],
    createdAt: '2026-07-02T11:30:00Z',
    updatedAt: '2026-07-04T13:45:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-104',
    title: 'Переключатель IP-адреса сервера в шапке портала',
    description: 'Добавить кнопку в Header, позволяющую сотрудникам в один клик указать IP-адрес центрального ноутбука в Wi-Fi сети.',
    status: 'in-progress',
    priority: 'medium',
    assigneeId: 'usr-4',
    assignee: 'usr-4',
    assigneeGroupId: 'grp-1',
    storyPoints: 3,
    estimatedHours: 6,
    loggedHours: 4,
    sprintId: 'sprint-1',
    tags: ['Frontend', 'UI/UX'],
    createdAt: '2026-07-03T14:00:00Z',
    updatedAt: '2026-07-04T16:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-105',
    title: 'Оптимизация рендеринга доски задач до 60 FPS',
    description: 'Удалить тяжелые backdrop-filter: blur и непрерывные transition: all для мгновенного отклика при перетаскивании карточек на любых ноутбуках.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-3',
    assignee: 'usr-3',
    assigneeGroupId: 'grp-1',
    storyPoints: 5,
    estimatedHours: 10,
    loggedHours: 10,
    sprintId: 'sprint-1',
    tags: ['Frontend', 'Architecture'],
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-04T11:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-106',
    title: 'Разработка личного кабинета сотрудника («Моя страница»)',
    description: 'Создать вкладку с персональной статистикой KPI, отработанными часами, Story Points и списком закрепленных задач.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'usr-7',
    assignee: 'usr-7',
    assigneeGroupId: 'grp-4',
    storyPoints: 5,
    estimatedHours: 14,
    loggedHours: 14,
    sprintId: 'sprint-1',
    tags: ['UI/UX', 'Frontend'],
    createdAt: '2026-07-02T15:00:00Z',
    updatedAt: '2026-07-04T13:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-107',
    title: 'Внедрение ролевой модели разграничения прав (RBAC)',
    description: 'Запретить обычным сотрудникам редактировать параметры чужих задач. Ограничить доступ к админской панели только для роли Admin.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'usr-8',
    assignee: 'usr-8',
    assigneeGroupId: 'grp-1',
    storyPoints: 8,
    estimatedHours: 16,
    loggedHours: 16,
    sprintId: 'sprint-1',
    tags: ['Security', 'Backend', 'Frontend'],
    createdAt: '2026-07-01T12:00:00Z',
    updatedAt: '2026-07-04T13:30:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-108',
    title: 'Подготовка E2E тестов для автоматизированного тестирования задач',
    description: 'Написать сценарии проверки жизненного цикла задачи: создание -> взятие в работу -> проверка -> завершение.',
    status: 'review',
    priority: 'medium',
    assigneeId: 'usr-6',
    assignee: 'usr-6',
    assigneeGroupId: 'grp-3',
    storyPoints: 5,
    estimatedHours: 16,
    loggedHours: 14,
    sprintId: 'sprint-1',
    tags: ['QA', 'Architecture'],
    createdAt: '2026-07-03T16:00:00Z',
    updatedAt: '2026-07-04T15:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-109',
    title: 'Формирование продуктовой дорожной карты (Roadmap) на Q3',
    description: 'Согласование ключевых эпиков спринта с руководителями отделов и планирование релизных дат.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-5',
    assignee: 'usr-5',
    assigneeGroupId: 'grp-2',
    storyPoints: 5,
    estimatedHours: 14,
    loggedHours: 14,
    sprintId: 'sprint-1',
    tags: ['Product', 'Agile'],
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-03T18:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-110',
    title: 'Проведение Scrum-планирования и ежедневных Daily-митингов',
    description: 'Синхронизация членов команды, снятие блокеров по задачам разработки и тестирования.',
    status: 'in-progress',
    priority: 'medium',
    assigneeId: 'usr-10',
    assignee: 'usr-10',
    assigneeGroupId: 'grp-2',
    storyPoints: 3,
    estimatedHours: 10,
    loggedHours: 6,
    sprintId: 'sprint-1',
    tags: ['Scrum', 'Management'],
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-04T11:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-111',
    title: 'Аналитика и построение графиков KPI в PDF отчете',
    description: 'Анализ распределения Story Points между сотрудниками, выгрузка детальных метрик в формате отчетов.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-11',
    assignee: 'usr-11',
    assigneeGroupId: 'grp-2',
    storyPoints: 5,
    estimatedHours: 12,
    loggedHours: 12,
    sprintId: 'sprint-1',
    tags: ['Analytics', 'BI', 'PDF'],
    createdAt: '2026-07-02T14:00:00Z',
    updatedAt: '2026-07-04T16:00:00Z',
    subtasks: [],
    comments: []
  },
  {
    id: 'NEX-112',
    title: 'Оптимизация базы данных PostgreSQL и индексов поиска',
    description: 'Профилирование медленных запросов при выборке больших объемов задач за спринт.',
    status: 'in-progress',
    priority: 'urgent',
    assigneeId: 'usr-8',
    assignee: 'usr-8',
    assigneeGroupId: 'grp-1',
    storyPoints: 8,
    estimatedHours: 18,
    loggedHours: 10,
    sprintId: 'sprint-2',
    tags: ['Backend', 'Database'],
    createdAt: '2026-07-03T11:00:00Z',
    updatedAt: '2026-07-04T17:00:00Z',
    subtasks: [],
    comments: []
  }
];

export const initialGroups = [
  {
    id: 'grp-1',
    name: '🚀 Команда Разработки (Engineering)',
    color: '#3b82f6',
    memberIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4', 'usr-8', 'usr-9']
  },
  {
    id: 'grp-2',
    name: '🎯 Менеджмент и Продукт (Product & Agile)',
    color: '#8b5cf6',
    memberIds: ['usr-5', 'usr-10', 'usr-11']
  },
  {
    id: 'grp-3',
    name: '🛡️ Отдел Тестирования (Quality Assurance)',
    color: '#10b981',
    memberIds: ['usr-6']
  },
  {
    id: 'grp-4',
    name: '🎨 Дизайн и UX (Design Team)',
    color: '#ec4899',
    memberIds: ['usr-7']
  }
];
